### ISSUE TITLE
Display dialog with conditions details

### ISSUE THREAD

**Issue by orontee** [orontee/taranis#16]
# Context

I sometime wants to read the UV index or compare raw and felt temperatures. It's impossible to display all information on the daily forecast nor the hourly forecast.

# Analysis

Display a dialog with condition details. Possible for both daily and hourly forecast.

Just start with daily forecast.

## TODO
- [x] Wind direction
- [x] Moon phase (See #42)
- [x] Dew point
- ~Replace temperatures table with a plot~ (non-sense since no time for min and max and no felt extrema)
- [x] Weather icon
- [x] Secondary weather description
- ~Draw separators, not empty lines~
- [x] Close button
- [ ] Scrollbar
- [x] Translations (French is already done)
- ~Elide long values~ (may not be needed...)

## Remarks

* A bug in current deserialization of felt temperatures will explain users seeing wrong values if they start the application with an up-to-date cache.
* Secondary weather description (the `summary` property of OpenWeather API response) isn't translated; It's shown iff current language is English.

**Comment by orontee** [comment]
Current rendering is ugly...


![scr0006](https://github.com/orontee/taranis/assets/2065954/0b8485da-999e-40bb-93c9-8cbc955b10e9)

**Comment by orontee** [comment]
Not sure this feature is still needed...

**Comment by orontee** [comment]
New version, implemented as a modal widget.

Already working, wanted information are present, but still needs some style improvement.

![scr0018](https://github.com/user-attachments/assets/3d859b6a-c034-4eb1-aabe-abbb7f8b3a8f)

**Comment by orontee** [comment]
Made some changes:
- Modal dialogs aren't necessarily full screen anymore
- Add wind direction

Still missing:
- Weather icon
- Weather secondary description when available
- Moon phase

![daily_forecast_dialog](https://github.com/user-attachments/assets/f13bebd5-2cb4-4225-a385-1d7318349262)

**Comment by orontee** [comment]
![daily_forecast_dialog](https://github.com/user-attachments/assets/c80961ca-9f37-4914-98b0-baacb17d9791)

**Comment by orontee** [comment]
Temperatures should be transposed to fill four rows only and wind information should occupy a single line. To limit need for scrolling, improve readability, and be coherent with temperatures in daily forecast box.
